<a href="https://colab.research.google.com/github/sweeeet-zoo/sparta5/blob/main/%EC%8B%A4%EC%A0%84%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%88%98%EC%A7%91_%ED%85%8C%EC%8A%A4%ED%8A%B8_0310.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests

### 마이크로 유튜버 데이터_테스트 from 세진님

In [ ]:
# YouTube API 키
API_KEY = "AIzaSyCcdwkU-RdUORv5SzBEFpBQSpdr7NRQbjw"
BASE_URL = "https://www.googleapis.com/youtube/v3"

# 한국 유튜버를 찾기 위한 검색 키워드
SEARCH_KEYWORDS = ["메이크업", "화장", "코스메틱", "뷰티", "비포에프터", "커버메이크업", "겟레디위드미", "코스매틱"]

def get_top_youtubers(min_subs=10_000, max_subs=100_000, max_results=200):
    """구독자 10,000~100,000명 사이의 한국 유튜버 TOP 200을 찾는 함수"""
    top_channels = set()  # 중복 방지를 위해 set 사용

    for keyword in SEARCH_KEYWORDS:
        search_url = f"{BASE_URL}/search"
        params = {
            "part": "snippet",
            "q": keyword,  # 한국어 키워드 검색
            "regionCode": "KR",  # 한국 유튜버 검색
            "relevanceLanguage": "ko",  # 한국어 콘텐츠 우선순위 설정
            "maxResults": 50,
            "type": "channel",
            "key": API_KEY
        }

        response = requests.get(search_url, params=params).json()
        if "items" not in response:
            continue

        channel_ids = [item["id"]["channelId"] for item in response["items"]]

        # 채널 정보 가져오기
        channel_url = f"{BASE_URL}/channels"
        params = {
            "part": "snippet,statistics",
            "id": ",".join(channel_ids),
            "key": API_KEY
        }
        channel_response = requests.get(channel_url, params=params).json()

        for item in channel_response.get("items", []):
            subs_count = int(item["statistics"].get("subscriberCount", 0))
            if min_subs <= subs_count <= max_subs:
                channel_info = (
                    item["snippet"]["title"],
                    item["id"],
                    subs_count
                )
                top_channels.add(channel_info)

        if len(top_channels) >= max_results:
            break

    # 구독자 수 기준으로 정렬 후 상위 200개 선택
    top_channels = sorted(list(top_channels), key=lambda x: x[2], reverse=True)[:max_results]

    return top_channels

# 실행
top_youtubers = get_top_youtubers()
if top_youtubers:
    print("\n📢 구독자 10,000~100,000명 사이의 한국 유튜버 TOP 200 📢")
    for i, (title, channel_id, subs) in enumerate(top_youtubers, start=1):
        print(f"{i}. {title} - {subs} subscribers")
else:
    print("No data found")

📢 구독자 10,000~100,000명 사이의 한국 유튜버 TOP 200 📢
1. 딘디DINDIHYE - 71400 subscribers
2. 이너뷰티 휘연 - 69900 subscribers
3. 메리 - 65900 subscribers
4. 호호뷰티 - 65100 subscribers
5. 까퓰러ASMR Gapular - 63300 subscribers
6. 1분뷰티 셀프피부 - 63100 subscribers
7. 뷰티멘토아리아 - 60000 subscribers
8. 엘리 메이크업 - 59700 subscribers
9. 로맨틱민서 MINSEO - 59400 subscribers
10. 뷰티나니?BeautyNANI? - 56500 subscribers
11. 고수뷰티 GOSOO BEAUTY - 52400 subscribers
12. 후메이크업whozmakeup - 50000 subscribers
13. 디오드 뷰티 - 48300 subscribers
14. 뷰티랩스 - 44300 subscribers
15. 신지훈의 뷰티비 - make up - 35800 subscribers
16. 팔로잉미 - 35200 subscribers
17. 몽데이MONGDAY - 29900 subscribers
18. 현슈슈 hyunshushu - 24600 subscribers
19. 혠 - 22800 subscribers
20. 로하우스 뷰티 - 19400 subscribers
21. 화장의 신프로 Makeup Shin Prof. - 16200 subscribers
22. 하우스리페어 - 15800 subscribers
23. 최민낯_민낯뷰티 - 15300 subscribers
24. 꼬솜 GOSOM - 12700 subscribers
25. 메멘토설은 - 12600 subscribers
26. DAKYO 다교쌤 - 11100 subscribers
27. 리아뷰티 Lia Beauty - 10500 subscribers
28. 윤커벨 younkerbell - 10100 subscribers
29. 봄이 - 10100 subscribers

### 제목 조건 추가 from 지우님

In [ ]:
from googleapiclient.discovery import build
import time

API_KEY = "AIzaSyCcdwkU-RdUORv5SzBEFpBQSpdr7NRQbjw"
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"

youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=API_KEY)

# 기준
RANGES = {
    "mega": (1000000, float("inf")),
    "macro": (100000, 1000000),
    "micro": (10000, 100000),
}

BEAUTY_KEYWORDS = ["메이크업", "makeup", "make up", "화장", "스킨케어", "뷰티", "코스메틱"]


def get_top_channels_by_subscribers(max_results=200):
    """뷰티 관련 영상을 올리는 유튜버 중 상위 max_results명 추출"""
    all_channels = set()  # 중복 방지
    channel_list = []
    next_page_token = None

    while len(channel_list) < max_results:
        request = youtube.search().list(
            part="snippet",
            q='메이크업 makeup "make up" 화장 스킨케어 뷰티 코스메틱',
            type="video",
            maxResults=10,
            pageToken=next_page_token
        )
        response = request.execute()

        for item in response.get("items", []):
            channel_id = item["snippet"]["channelId"]
            title = item["snippet"]["channelTitle"]

            if channel_id not in all_channels:
                all_channels.add(channel_id)
                channel_list.append({"channel_id": channel_id, "title": title})

        next_page_token = response.get("nextPageToken")
        if not next_page_token:
            break

        time.sleep(3)

    return channel_list[:max_results]


def get_channel_details(channel_ids):
    """채널 정보를 가져와 구독자 수 기준으로 분류"""
    influencer_data = { "mega": [], "macro": [], "micro": [] }

    for i in range(0, len(channel_ids), 10):
        request = youtube.channels().list(
            id=",".join(channel_ids[i:i+10]),
            part="snippet,statistics"
        )
        response = request.execute()

        for item in response.get("items", []):
            title = item["snippet"]["title"]
            channel_id = item["id"]
            subscriber_count = int(item["statistics"].get("subscriberCount", 0))

            for category, (min_subs, max_subs) in RANGES.items():
                if min_subs <= subscriber_count < max_subs:
                    influencer_data[category].append({
                        "title": title,
                        "channel_id": channel_id,
                        "subscriber_count": subscriber_count,
                    })
                    break

        time.sleep(3)

    return influencer_data


def check_beauty_content(channel_id):
    """해당 유튜버의 재생목록과 최근 동영상에서 뷰티 관련 키워드 포함 여부 확인"""
    # 재생목록 확인
    playlist_request = youtube.playlists().list(
        part="snippet",
        channelId=channel_id,
        maxResults=10
    )
    playlist_response = playlist_request.execute()

    for item in playlist_response.get("items", []):
        playlist_title = item["snippet"]["title"].lower()
        if any(keyword.lower() in playlist_title for keyword in BEAUTY_KEYWORDS):
            return True

    # 최신 동영상에서 확인
    video_request = youtube.search().list(
        part="snippet",
        channelId=channel_id,
        maxResults=10,
        order="date",
        type="video"
    )
    video_response = video_request.execute()

    for item in video_response.get("items", []):
        video_title = item["snippet"]["title"].lower()
        video_description = item["snippet"].get("description", "").lower()
        if any(keyword.lower() in video_title or keyword.lower() in video_description for keyword in BEAUTY_KEYWORDS):
            return True

    return False


def filter_beauty_influencers(influencer_data):
    """뷰티 관련 키워드를 포함하는 유튜버 필터링"""
    final_influencers = { "mega": [], "macro": [], "micro": [] }

    for category, influencers in influencer_data.items():
        for influencer in influencers:
            if check_beauty_content(influencer["channel_id"]):
                final_influencers[category].append(influencer)

            if len(final_influencers[category]) >= 100:
                break

    return final_influencers


if __name__ == "__main__":
    print("🔍 유튜버 수집 중...")
    top_channels = get_top_channels_by_subscribers()

    channel_ids = [ch["channel_id"] for ch in top_channels]
    print(f"✅ {len(channel_ids)}개의 채널 ID 수집 완료. 구독자 수 확인 중...")
    influencers = get_channel_details(channel_ids)

    print("💄 뷰티 유튜버 필터링 중...")
    beauty_influencers = filter_beauty_influencers(influencers)

    for category, data in beauty_influencers.items():
        print(f"\n🎯 {category.upper()} 인플루언서 TOP {len(data)}:")
        for idx, influencer in enumerate(data, start=1):
            print(f"{idx}. {influencer['title']} ({influencer['subscriber_count']}명) - https://www.youtube.com/channel/{influencer['channel_id']}")

🔍 유튜버 수집 중...
✅ 200개의 채널 ID 수집 완료. 구독자 수 확인 중...
💄 뷰티 유튜버 필터링 중...

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "quotaExceeded"

HttpError: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/search?part=snippet&channelId=UCJxRLFtdyqGBtQOw8VWRlrw&maxResults=10&order=date&type=video&key=AIzaSyCcdwkU-RdUORv5SzBEFpBQSpdr7NRQbjw&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">

### 국가별 마이크로 인플루언서 데이터 수집_테스트

In [ ]:
# YouTube API 키
API_KEY = "AIzaSyCcdwkU-RdUORv5SzBEFpBQSpdr7NRQbjw"
BASE_URL = "https://www.googleapis.com/youtube/v3"

# 한국 유튜버를 찾기 위한 검색 키워드
SEARCH_KEYWORDS = ["메이크업", "화장", "코스메틱", "뷰티", "비포에프터", "커버메이크업", "겟레디위드미", "코스매틱", "cosmetic", "Cosmetic", "Beauty", "beauty", "makeup", "Makeup", "make up", "Make up", "Make Up"]

def get_top_youtubers(min_subs=10_000, max_subs=100_000, max_results=200):
    """구독자 10,000~100,000명 사이의 한국 유튜버 TOP 200을 찾는 함수"""
    top_channels = set()  # 중복 방지를 위해 set 사용

    for keyword in SEARCH_KEYWORDS:
        search_url = f"{BASE_URL}/search"
        params = {
            "part": "snippet",
            "q": keyword,  # 한국어 키워드 검색  # 한국 유튜버 검색
            "relevanceLanguage": "ko",  # 한국어 콘텐츠 우선순위 설정
            "maxResults": 50,
            "type": "channel",
            "key": API_KEY
        }

        response = requests.get(search_url, params=params).json()
        if "items" not in response:
            continue

        channel_ids = [item["id"]["channelId"] for item in response["items"]]

        # 채널 정보 가져오기
        channel_url = f"{BASE_URL}/channels"
        params = {
            "part": "snippet,statistics",
            "id": ",".join(channel_ids),
            "key": API_KEY
        }
        channel_response = requests.get(channel_url, params=params).json()

        for item in channel_response.get("items", []):
            subs_count = int(item["statistics"].get("subscriberCount", 0))
            if min_subs <= subs_count <= max_subs:
                channel_info = (
                    item["snippet"]["title"],
                    item["id"],
                    subs_count
                )
                top_channels.add(channel_info)

        if len(top_channels) >= max_results:
            break

    # 구독자 수 기준으로 정렬 후 상위 200개 선택
    top_channels = sorted(list(top_channels), key=lambda x: x[2], reverse=True)[:max_results]

    return top_channels

# 실행
top_youtubers = get_top_youtubers()
if top_youtubers:
    print("\n📢 구독자 10,000~100,000명 사이의 한국 유튜버 TOP 200 📢")
    for i, (title, channel_id, subs) in enumerate(top_youtubers, start=1):
        print(f"{i}. {title} - {subs} subscribers")
else:
    print("No data found")

No data found

In [ ]:
# YouTube API 키
API_KEY = "AIzaSyBsm4pvfk_reCWBd_c5ySRPxuyYT3KJci8"
BASE_URL = "https://www.googleapis.com/youtube/v3"

# 한국 유튜버를 찾기 위한 검색 키워드
SEARCH_KEYWORDS = ["메이크업", "Makeup", "makeup", "MAKEUP", "MakeUp", "make up", "makeUp", "Makeup", "Make Up", "MAKE UP", "뷰티", "Beauty", "beauty", "BEAUTY", "코스메틱", "코스매틱", 'COSMETIC', "cosmetic", "Cosmetic"]

def get_top_youtubers(min_subs=500_000, max_subs=1_000_000, max_results=200):
    """구독자 500,000~6,000,000명 사이의 한국 유튜버 TOP 200을 찾는 함수"""
    top_channels = set()  # 중복 방지를 위해 set 사용

    for keyword in SEARCH_KEYWORDS:
        search_url = f"{BASE_URL}/search"
        params = {
            "part": "snippet",
            "q": keyword,  # 한국어 키워드 검색  # 한국 유튜버 검색
            "maxResults": 50,
            "type": "channel",
            "key": API_KEY
        }

        response = requests.get(search_url, params=params).json()
        if "items" not in response:
            continue

        channel_ids = [item["id"]["channelId"] for item in response["items"]]

        # 채널 정보 가져오기
        channel_url = f"{BASE_URL}/channels"
        params = {
            "part": "snippet,statistics",
            "id": ",".join(channel_ids),
            "key": API_KEY
        }
        channel_response = requests.get(channel_url, params=params).json()

        for item in channel_response.get("items", []):
            subs_count = int(item["statistics"].get("subscriberCount", 0))
            country = item.get("snippet", {}).get("country", "Unknown")

            if min_subs <= subs_count <= max_subs:
                channel_info = (
                    item["snippet"]["title"],
                    item["id"],
                    country,
                    subs_count
                )
                top_channels.add(channel_info)

        if len(top_channels) >= max_results:
            break

    # 구독자 수 기준으로 정렬 후 상위 200개 선택
    top_channels = sorted(list(top_channels), key=lambda x: x[2], reverse=True)[:max_results]

    return top_channels

### 재생목록 기준 검색

In [ ]:
# YouTube API 키
API_KEY = "AIzaSyAXcyW687GW8DvGks2T2OjKitE-6mHB7vs"
BASE_URL = "https://www.googleapis.com/youtube/v3"

# 한국 유튜버를 찾기 위한 검색 키워드
SEARCH_KEYWORDS = ["메이크업", "Makeup", "makeup", "MAKEUP", "MakeUp", "make up", "makeUp", "Makeup", "Make Up", "MAKE UP", "뷰티", "Beauty", "beauty", "BEAUTY", "코스메틱", "코스매틱", 'COSMETIC', "cosmetic", "Cosmetic"]

def get_top_youtubers(min_subs=500_000, max_subs=6_000_000, max_results=500):
    top_channels = set()  # 중복 방지를 위해 set 사용
    """구독자 500,000~6,000,000명 사이의 한국 유튜버 TOP 200을 찾는 함수"""

    for keyword in SEARCH_KEYWORDS:
        search_url = f"{BASE_URL}/search"
        params = {
            "part": "snippet",
            "q": keyword,  # 한국어 키워드 검색  # 한국 유튜버 검색
            "maxResults": 500,
            "type": "playlist",
            "key": API_KEY
        }

        response = requests.get(search_url, params=params).json()
        if "items" not in response:
            continue

        channel_ids = [item["snippet"]["channelId"] for item in response["items"]]

        # 채널 정보 가져오기
        channel_url = f"{BASE_URL}/channels"
        params = {
            "part": "snippet,statistics",
            "id": ",".join(channel_ids),
            "key": API_KEY
        }
        channel_response = requests.get(channel_url, params=params).json()

        for item in channel_response.get("items", []):
            subs_count = int(item["statistics"].get("subscriberCount", 0))
            country = item.get("snippet", {}).get("country", "Unknown")

            if country == 'KR' and min_subs <= subs_count <= max_subs:
                channel_info = (
                    item["snippet"]["title"],
                    item["id"],
                    country,
                    subs_count
                )
                top_channels.add(channel_info)

        if len(top_channels) >= max_results:
            break

    # 구독자 수 기준으로 정렬 후 상위 200개 선택
    top_channels = sorted(list(top_channels), key=lambda x: x[3], reverse=True)[:max_results]

    return top_channels

In [ ]:
# 실행
top_youtubers = get_top_youtubers()
top_youtubers

[('스마일밤 Smile Bam', 'UCKo9E6a6-E40CC6OdSbvcdA', 'KR', 5260000),
 ('JTBC Drama', 'UCkbJc8jMcTXwhtmN5VMwfXg', 'KR', 4930000),
 ('화장하는청담언니', 'UCrCdZl27CS-SlBDpNDZZ-qw', 'KR', 2720000),
 ('안다 ANDA', 'UCn_fZLXut_Tj9-QihG_9l0g', 'KR', 1460000),
 ('ssin 씬님', 'UC5xK2Xdrud3-KGjkS1Igumg', 'KR', 1430000),
 ('양팡 YangPang', 'UCMVC92EOs9yDJG5JS-CMesQ', 'KR', 1420000),
 ("써니채널 Sunny's Channel", 'UCxM21Vv4bWq106MxIPvrGQw', 'KR', 1160000),
 ('박막례 할머니 Korea_Grandma', 'UCN8CPzwkYiDVLZlgD4JQgJQ', 'KR', 1150000),
 ('윤쨔미 YoonCharmi', 'UCQtPAu0FjPbA1ku3cA5R2mg', 'KR', 905000),
 ('Myaling ASMR', 'UC6fAYCOjXMzb1K07i0G5gOQ', 'KR', 777000),
 ('Bora Claire (보라끌레르)', 'UCSrRZH9QT6li5PIAv0r_6QA', 'KR', 748000),
 ('STUDIO DIA 스튜디오 다이아', 'UCjOslp-74AgL4gaUWvojZbw', 'KR', 721000),
 ('헤이즐 Heizle', 'UCO-7CJCtOqw1yqh3y8owGfg', 'KR', 655000),
 ('JUNGSAEMMOOL', 'UCtCpkkzNnYixE9GEJVaCI8g', 'KR', 649000),
 ('태리태리 taeritaeri', 'UCC9XEedRtiWNIVrSI-JayZw', 'KR', 603000),
 ('Yoo True', 'UCH2mJnztSdNh8ADp2KmtUMQ', 'KR', 576000)]

In [ ]:
if top_youtubers:
    print("\n📢 구독자 10,000~100,000명 사이의 한국 유튜버 TOP 200 📢")
    for i, (title, channel_id, country,subs) in enumerate(top_youtubers, start=1):
        print(f"{i}. {title} - {subs} subscribers")
else:
    print("No data found")

📢 구독자 10,000~100,000명 사이의 한국 유튜버 TOP 200 📢
1. 아옳이 - 761000 subscribers
2. Troom Troom Kr - 1000000 subscribers
3. 김습습Double Soup - 688000 subscribers
4. Yoo True - 576000 subscribers
5. 금단미인 - 665000 subscribers
6. STUDIO DIA 스튜디오 다이아 - 721000 subscribers
7. JUNGSAEMMOOL - 649000 subscribers
8. 로즈하 ROSEHA - 612000 subscribers
9. 태리태리 taeritaeri - 603000 subscribers
10. 윤쨔미 YoonCharmi - 905000 subscribers
11. Bora Claire (보라끌레르) - 748000 subscribers
12. 헤이즐 Heizle - 655000 subscribers

In [ ]:
df_list = list(top_youtubers)

In [ ]:
import pandas as pd

In [ ]:
df_frame = pd.DataFrame(df_list, columns=['title', 'channel_id', 'country', 'subs'])
df_frame.head()

                  title                channel_id  country   subs
0  DADA Beauty Việt Nam  UCPmRCW7r3tBKyMQy8ZfXwZw       VN  15800
1       Trangsun Makeup  UCgjCnDjx-G40tx3xgDlq2YQ       VN  78800
2       Tina Lê Make Up  UC4Y7jRD9Al5JBqDoMHkibrQ       VN  48400
3       Love for Makeup  UCxjhuF1jfELznbqiQ6arGvw  Unknown  12700
4                  호호뷰티  UCKycl5tLdiOz6CMoRMpXNjA  Unknown  65100

In [ ]:
df_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       66 non-null     object
 1   channel_id  66 non-null     object
 2   country     66 non-null     object
 3   subs        66 non-null     int64
dtypes: int64(1), object(3)
memory usage: 2.2+ KB

In [ ]:
df_korea = df_frame.loc[df_frame['country']=='KR']
df_korea

                        title                channel_id country   subs
32                  1분뷰티 셀프피부  UCVuxljGhpSkXztzk8X6vlMQ      KR  63100
33         신지훈의 뷰티비 - make up  UC8ztEunx83lflUWENoMdAuA      KR  35800
34            리아뷰티 Lia Beauty  UCAXVvaPOmb19eThQR-fLpKg      KR  10500
35                       찌니뷰티  UCwXb4wWwhFNYHedz_g9Q8qw      KR  12500
36            후메이크업whozmakeup  UCw30nojSCDiqv1JO0Tu1Mrw      KR  50000
37                    엘리 메이크업  UCT2aO5ha79Yu-HN6U_PNlCg      KR  59700
38                   최민낯_민낯뷰티  UCjye-yA-LIb7WXKRnGR-fzA      KR  15300
39  화장의 신프로 Makeup Shin Prof.  UCyAmQPPLTsy-B2NhQKo3KMg      KR  16200
40                       뷰티랩스  UC9BEygCDE2B7vB5tIgpsIDg      KR  44300
41          고수뷰티 GOSOO BEAUTY  UC53ZbBCHU_N49ykaxeCcAGg      KR  52400
42                     디오드 뷰티  UCJf_CZp5YjzW4GM6G2uZC6w      KR  48300

### 동영상 기준 재생목록 검색

In [ ]:
# YouTube API 키
API_KEY = "AIzaSyDzaz-AIxZCx_nrKDjiOQpSgaQiZ743y78"
BASE_URL = "https://www.googleapis.com/youtube/v3"

# 한국 유튜버를 찾기 위한 검색 키워드
SEARCH_KEYWORDS = ["메이크업", "커버 메이크업", "화장품 추천", "요즘 메이크업", "올리브영", "올영 추천", "웜톤", "쿨톤", "GRWM 메이크업", ]

def get_video_youtubers(min_subs=500_000, max_subs=6_000_000, max_results=1000):
    video_channels = set()  # 중복 방지를 위해 set 사용
    """구독자 500,000~6,000,000명 사이의 한국 유튜버 TOP 200을 찾는 함수"""

    for keyword in SEARCH_KEYWORDS:
        search_url = f"{BASE_URL}/search"
        params = {
            "part": "snippet",
            "q": keyword,  # 한국어 키워드 검색  # 한국 유튜버 검색
            "maxResults": 1000,
            "type": "video",
            "order" : "viewCount",
            "key": API_KEY
        }

        response = requests.get(search_url, params=params).json()
        if "items" not in response:
            continue

        channel_ids = [item["snippet"]["channelId"] for item in response["items"]]

        # 채널 정보 가져오기
        channel_url = f"{BASE_URL}/channels"
        params = {
            "part": "snippet,statistics",
            "id": ",".join(channel_ids),
            "key": API_KEY
        }
        channel_response = requests.get(channel_url, params=params).json()

        for item in channel_response.get("items", []):
            subs_count = int(item["statistics"].get("subscriberCount", 0))
            country = item.get("snippet", {}).get("country", "Unknown")

            if country == 'KR' and min_subs <= subs_count <= max_subs:
                channel_info = (
                    item["snippet"]["title"],
                    item["id"],
                    country,
                    subs_count
                )
                video_channels.add(channel_info)

        if len(top_channels) >= max_results:
            break

    # 구독자 수 기준으로 정렬 후 상위 200개 선택
    video_channels = sorted(list(video_channels), key=lambda x: x[3], reverse=True)[:max_results]

    return video_channels

In [ ]:
# 실행
video_youtubers = get_video_youtubers()
video_youtubers

[('PONY Syndrome', 'UCT-_4GqC-yLY1xtTHhwY0hA', 'KR', 5900000),
 ('tvN D ENT', 'UCsRIHt5FkbGc6cQtCxt-ufA', 'KR', 5100000),
 ('워크맨-Workman', 'UCwx6n_4OcLgzAGdty0RWCoA', 'KR', 4180000),
 ('숏박스', 'UC1B6SalAoiJD7eHfMUA9QrA', 'KR', 3260000),
 ('RISABAE', 'UC9kmlDcqksaOnCkC_qzGacA', 'KR', 2550000),
 ('창하CHANGHA', 'UCX4H3pl79Gs0Y-fbqwXiyzw', 'KR', 2440000),
 ('혜리', 'UC2tfQfxl_wmAosF4ES_zULw', 'KR', 2120000),
 ('효진조 Hyojin Cho', 'UCuZu8NrpBG4WPXRi-hPBl-A', 'KR', 1900000),
 ('미미미누', 'UCyNHdF4hMxHUFSsPbY24p6A', 'KR', 1780000),
 ('안다 ANDA', 'UCn_fZLXut_Tj9-QihG_9l0g', 'KR', 1460000),
 ('LeoJ Makeup', 'UCnFFOjljp1_sacTz7PfIIyg', 'KR', 1400000),
 ('Official fromis_9', 'UC8qO5racajmy4YgPgNJkVXg', 'KR', 1290000),
 ('탱구TV', 'UC5z2fxN6rs69cSyXur6X6Mg', 'KR', 1200000),
 ('세아쌤Seah Ssam', 'UCs4wUolAHK6DONFmUBJIOHA', 'KR', 1190000),
 ("써니채널 Sunny's Channel", 'UCxM21Vv4bWq106MxIPvrGQw', 'KR', 1160000),
 ('박막례 할머니 Korea_Grandma', 'UCN8CPzwkYiDVLZlgD4JQgJQ', 'KR', 1150000),
 ('사내뷰공업 beautyfool', 'UCeS6R89S32mSOxTNoEqrN7g', 'KR', 1130000),
 ('나는조이서 Joyseo', 'UCfbmmjCKPAxzLxeKqpg25vQ', 'KR', 1060000),
 ('조나단', 'UCM9Rx3EqBJ-jMhD2E8Gjb4g', 'KR', 957000),
 ('뚜식이', 'UCUK4YjvUvHrFQwTFXwkUIng', 'KR', 947000),
 ('Saerom Min개코의 오픈스튜디오', 'UCI0ELrUDa91NauGqFn1IWow', 'KR', 931000),
 ('윤쨔미 YoonCharmi', 'UCQtPAu0FjPbA1ku3cA5R2mg', 'KR', 905000),
 ('뷰티메이크업', 'UCApUHaDVHeE5f1WX3JXQ21g', 'KR', 791000),
 ('금손언니', 'UCByWzwpRxPDrm1VdJU-Ixug', 'KR', 772000),
 ('임한올 Hanol Rim', 'UCsi1IIpdyXozNFpuf4k5jvg', 'KR', 764000),
 ('트윈데이 TWINDAY', 'UCkTou95-Hb_GJ6IG5MxuyDA', 'KR', 759000),
 ('동네 의사 이상욱', 'UC0TR0Ciw0rQSJzgU5NiwvRQ', 'KR', 733000),
 ('대환장파티', 'UCf1B5oZs8jVL49Mkmv91upg', 'KR', 723000),
 ('yeondukong 연두콩', 'UCAUbDYDwV34yk6pYiZg_CzA', 'KR', 721000),
 ('Minsco 민스코', 'UCTQGAYPtbnCEfW9IGx65kiw', 'KR', 719000),
 ('유앤아인Youandain', 'UCjPyAhNXoY0c8v0B3rr-D2Q', 'KR', 598000),
 ('Yoo True', 'UCH2mJnztSdNh8ADp2KmtUMQ', 'KR', 576000),
 ('쉐리 SHERRY', 'UCnbQutaGtu6EOKYnwT35Etg', 'KR', 554000),
 ('탐구생활 - 돈이 되는 삶의 이야기', 'UCBbJv4YWyu89pP1tg9laatw', 'KR', 544000),
 ('뷰드름 유튜버 인씨', 'UCrlUlicedicJ5mlibqC62Eg', 'KR', 535000),
 ('INBORA인보라', 'UCUrCIBJ3ScRAOLgPElscZqA', 'KR', 518000)]

In [ ]:
video_df_frame = pd.DataFrame(video_youtubers, columns=['title', 'channel_id', 'country', 'subs'])
print(video_df_frame.head())
print(video_df_frame.info())

           title                channel_id country     subs
0  PONY Syndrome  UCT-_4GqC-yLY1xtTHhwY0hA      KR  5900000
1      tvN D ENT  UCsRIHt5FkbGc6cQtCxt-ufA      KR  5100000
2    워크맨-Workman  UCwx6n_4OcLgzAGdty0RWCoA      KR  4180000
3            숏박스  UC1B6SalAoiJD7eHfMUA9QrA      KR  3260000
4        RISABAE  UC9kmlDcqksaOnCkC_qzGacA      KR  2550000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       36 non-null     object
 1   channel_id  36 non-null     object
 2   country     36 non-null     object
 3   subs        36 non-null     int64
dtypes: int64(1), object(3)
memory usage: 1.3+ KB
None

In [ ]:
video_df_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       37 non-null     object
 1   channel_id  37 non-null     object
 2   country     37 non-null     object
 3   subs        37 non-null     int64
dtypes: int64(1), object(3)
memory usage: 1.3+ KB

In [ ]:
video_df_korea = df_frame.loc[df_frame['country']=='KR']
video_df_korea

                        title                channel_id country   subs
32                  1분뷰티 셀프피부  UCVuxljGhpSkXztzk8X6vlMQ      KR  63100
33         신지훈의 뷰티비 - make up  UC8ztEunx83lflUWENoMdAuA      KR  35800
34            리아뷰티 Lia Beauty  UCAXVvaPOmb19eThQR-fLpKg      KR  10500
35                       찌니뷰티  UCwXb4wWwhFNYHedz_g9Q8qw      KR  12500
36            후메이크업whozmakeup  UCw30nojSCDiqv1JO0Tu1Mrw      KR  50000
37                    엘리 메이크업  UCT2aO5ha79Yu-HN6U_PNlCg      KR  59700
38                   최민낯_민낯뷰티  UCjye-yA-LIb7WXKRnGR-fzA      KR  15300
39  화장의 신프로 Makeup Shin Prof.  UCyAmQPPLTsy-B2NhQKo3KMg      KR  16200
40                       뷰티랩스  UC9BEygCDE2B7vB5tIgpsIDg      KR  44300
41          고수뷰티 GOSOO BEAUTY  UC53ZbBCHU_N49ykaxeCcAGg      KR  52400
42                     디오드 뷰티  UCJf_CZp5YjzW4GM6G2uZC6w      KR  48300

### type 섞어서 재생목록 검색

In [ ]:
# YouTube API 키
API_KEY = "AIzaSyCUYjMiGdbgQ6wWI1AiyygkWgZw8B_RO80"
BASE_URL = "https://www.googleapis.com/youtube/v3"

# 한국 유튜버를 찾기 위한 검색 키워드
# 평소 유튜브에서 검색하는 방식, 구어체 느낌을 좀 더 살려서 검색해도 괜찮을 듯
video_keywords = ["메이크업", "커버 메이크업", "화장품 추천", "요즘 메이크업", "올리브영", "올영 추천", "웜톤", "쿨톤", "GRWM 메이크업", "뷰티", "뷰티템", "매이크업", "느좋 메이크업", "데일리 메이크업", "증명사진 메이크업", "기초 화장"]

def get_type_youtubers(min_subs=500_000, max_subs=6_000_000, max_results=200):
    channels = set()  # 중복 방지를 위해 set 사용
    channel_ids = set()
    """구독자 500,000~6,000,000명 사이의 한국 유튜버 TOP 200을 찾는 함수"""

    # 비디오 타입에서 검색하기
    for keyword in video_keywords:
        for search_type in ["video", "playlist"]:
            search_url = f"{BASE_URL}/search"

            params = {
                  "part": "snippet",
                  "q": keyword,  # 한국어 키워드 검색  # 한국 유튜버 검색
                  "maxResults": 50,
                  "type" : search_type,
                  "order" : "relevance",
                  "key": API_KEY
              }
            response = requests.get(search_url, params=params).json()
            print("🔍 검색 결과 확인:", response)

            if "items" not in response:
                continue

            for item in response["items"]:
                channel_ids.update(item["snippet"]["channelId"])
                print(f"🔎 수집된 채널 ID: {channel_ids}")


        # 채널 정보 가져오기
        channel_url = f"{BASE_URL}/channels"
        params = {
            "part": "snippet,statistics",
            "id": ",".join(channel_ids),
            "key": API_KEY
        }
        channel_response = requests.get(channel_url, params=params).json()
        print("📡 채널 정보 응답 확인:", channel_response)

        for item in channel_response.get("items", []):
            subs_count = int(item["statistics"].get("subscriberCount", 0))
            country = item.get("snippet", {}).get("country", "Unknown")

            if country == 'KR' and min_subs <= subs_count <= max_subs:
                channel_info = (
                    item["snippet"]["title"],
                    item["id"],
                    country,
                    subs_count
                )
                channels.add(channel_info)

        if len(channels) >= max_results:
            break

    # 구독자 수 기준으로 정렬 후 상위 200개 선택
    channels = sorted(list(channels), key=lambda x: x[3], reverse=True)[:max_results]

    return channels

In [ ]:
# 실행
type_youtubers = get_type_youtubers()
type_youtubers

🔍 검색 결과 확인: {'kind': 'youtube#searchListResponse', 'etag': 'HsewMtrrQKaIMn4UBErfHH2xXkU', 'nextPageToken': 'CDIQAA', 'regionCode': 'US', 'pageInfo': {'totalResults': 1000000, 'resultsPerPage': 50}, 'items': [{'kind': 'youtube#searchResult', 'etag': '7bOd9Dx09nOFtQe0P2USWc4YWxk', 'id': {'kind': 'youtube#video', 'videoId': 'yCVgUh2yGdk'}, 'snippet': {'publishedAt': '2025-01-18T03:00:49Z', 'channelId': 'UCtCpkkzNnYixE9GEJVaCI8g', 'title': '블러셔 하나로 살리는 메이크업 디테일! ✨', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/yCVgUh2yGdk/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/yCVgUh2yGdk/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/yCVgUh2yGdk/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'JUNGSAEMMOOL', 'liveBroadcastContent': 'none', 'publishTime': '2025-01-18T03:00:49Z'}}, {'kind': 'youtube#searchResult', 'etag': 'z_ciUqI-Kjp8DjFp-wlazPFwJjU', 'id': {'kind': 'youtube#video', 'videoId': 'C03BMX5VcIM'}, 'snippet': {'publishedAt': '2024-10-13T12:29:31Z', 'channelId': 'UCK3L6x0ZGU-2cfTDMLnmUyw', 'title': '하루에 번호 3번 따인 메이크업..! 올리브영 추천템 #여쿨라이트', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/C03BMX5VcIM/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/C03BMX5VcIM/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/C03BMX5VcIM/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '진뉴 JINNEW', 'liveBroadcastContent': 'none', 'publishTime': '2024-10-13T12:29:31Z'}}, {'kind': 'youtube#searchResult', 'etag': 'yoUrOboyXqRLDE7YBsRZLqUDBt0', 'id': {'kind': 'youtube#video', 'videoId': 'yAkO9z6jJA0'}, 'snippet': {'publishedAt': '2022-11-05T12:05:55Z', 'channelId': 'UCKycl5tLdiOz6CMoRMpXNjA', 'title': '와..이렇게 한번만 화장해보세요...(데이지크,롬앤,네이밍,3CE)', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/yAkO9z6jJA0/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/yAkO9z6jJA0/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/yAkO9z6jJA0/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '호호뷰티', 'liveBroadcastContent': 'none', 'publishTime': '2022-11-05T12:05:55Z'}}, {'kind': 'youtube#searchResult', 'etag': 'VVb82ERYmVxrNiybErRX8zPIFag', 'id': {'kind': 'youtube#video', 'videoId': 'Z863SSarpbA'}, 'snippet': {'publishedAt': '2024-11-25T08:50:00Z', 'channelId': 'UCo9OPeVJL5hgPtwxUTEBgSA', 'title': '요즘 난리난! 트임 메이크업', 'description': '메이크업 #메이크업꿀팁 #메이크업꿀템 #뒷트임.', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/Z863SSarpbA/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/Z863SSarpbA/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/Z863SSarpbA/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '룡지니', 'liveBroadcastContent': 'none', 'publishTime': '2024-11-25T08:50:00Z'}}, {'kind': 'youtube#searchResult', 'etag': 'TWyDgC3xmdM0J4Zub-iGA36T070', 'id': {'kind': 'youtube#video', 'videoId': '_llYd_D-pkA'}, 'snippet': {'publishedAt': '2024-07-07T10:00:35Z', 'channelId': 'UCW67yGQxNNMnLqRHyaTjygA', 'title': '40대 이후 바꿔야할 메이크업 부위4곳‼️#makeuptutorial #kbeauty #홍이모', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/_llYd_D-pkA/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/_llYd_D-pkA/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/_llYd_D-pkA/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': "Hong's MakeuPlay 홍이모", 'liveBroadcastContent': 'none', 'publishTime': '2024-07-07T10:00:35Z'}}, {'kind': 'youtube#searchResult', 'etag': 'BLkemphIQVmsPJBuQDBe7jkBhEI', 'id': {'kind': 'youtube#video', 'videoId': 'n-RicDMp1_Y'}, 'snippet': {'publishedAt': '2025-01-01T10:00:43Z', 'channelId': 'UCW67yGQxNNMnLqRHyaTjygA', 'title': '‼️4050 필수시청 피부 화장은 이렇게 하세요 4050 잡티 커버하는 법 #kbeuty #홍이모 #잡티커버', 'description': '영상 속 제품 mustaev 스팟 이레이저 컨실러 펜슬 #01 퓨어 베이지 13000 KRW ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/n-RicDMp1_Y/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/n-RicDMp1_Y/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/n-RicDMp1_Y/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': "Hong's MakeuPlay 홍이모", 'liveBroadcastContent': 'none', 'publishTime': '2025-01-01T10:00:43Z'}}, {'kind': 'youtube#searchResult', 'etag': 'WxuMuw054ah-444e78xxinInFcE', 'id': {'kind': 'youtube#video', 'videoId': '3InEkr2YqjA'}, 'snippet': {'publishedAt': '2025-03-09T12:00:03Z', 'channelId': 'UCvOA4iVyEXF_W-YkzAACtrA', 'title': '모카무스이긴한데 쿨을 딱 한방울 넣어본 🤗🌰+🆒', 'description': 'instagram @happyrim business @conflow.company 넘버즈인 5번 글루타치온씨 흔적 필름 패드 에르보리앙 슈퍼비비 누드 + 비비 ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/3InEkr2YqjA/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/3InEkr2YqjA/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/3InEkr2YqjA/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'Happyrim혜림쌤', 'liveBroadcastContent': 'none', 'publishTime': '2025-03-09T12:00:03Z'}}, {'kind': 'youtube#searchResult', 'etag': 'TgmMO9b-QJrGyXw9PHif6DklU0k', 'id': {'kind': 'youtube#video', 'videoId': '1JWkNhvGAx8'}, 'snippet': {'publishedAt': '2024-11-27T10:33:22Z', 'channelId': 'UCbFbzOHmp04AS2ZkFSpQ4Og', 'title': '립 5개 바르는 사람의 립 메이크업 튜토리얼 #나연템', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/1JWkNhvGAx8/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/1JWkNhvGAx8/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/1JWkNhvGAx8/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '일단이나연 NAYEON', 'liveBroadcastContent': 'none', 'publishTime': '2024-11-27T10:33:22Z'}}, {'kind': 'youtube#searchResult', 'etag': 'HgldzLRo6KXCXnsR8RttSLo8i44', 'id': {'kind': 'youtube#video', 'videoId': 'Rh23Z13PvjM'}, 'snippet': {'publishedAt': '2025-01-18T11:00:34Z', 'channelId': 'UCZFKgRGh8IPGAp8IvUO_atg', 'title': '무쌍 필수👀 데일리 메이크업 쉬운 꿀팁 4가지⭐️ #메이크업 #무쌍', 'description': '(더보기)를 눌러주세용 ♥ - ✓등장제품 홀리카홀리카 마이 페이브 무드 아이 팔레트 데이지 (브러시 : 더툴랩 218 프리시전크리즈) ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/Rh23Z13PvjM/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/Rh23Z13PvjM/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/Rh23Z13PvjM/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '무쌍이다빈 DaBeen', 'liveBroadcastContent': 'none', 'publishTime': '2025-01-18T11:00:34Z'}}, {'kind': 'youtube#searchResult', 'etag': '-64pZQIBgODfVLK_VvggPmDMViA', 'id': {'kind': 'youtube#video', 'videoId': 'RCeDjeoXhc8'}, 'snippet': {'publishedAt': '2025-03-08T13:00:32Z', 'channelId': 'UCc_vOO8-XNMT8KmIVTEbt5g', 'title': '화알못 필수시청🔥내 메이크업만 촌스러운 이유⁉️ feat. 맑고 청순한 봄 데이트 메이크업 🌷💛 (또렷한데 자연스러운 브로우/같은 색조 다른 느낌/청순st 아이메이크업)', 'description': "contact mail : soyoon@lefericreator.com https://www.instagram.com/ahsy_u/ 이 영상은 '에스쁘아' 의 유료광고가 포함되어 있는 ...", 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/RCeDjeoXhc8/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/RCeDjeoXhc8/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/RCeDjeoXhc8/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '소윤Soyoon', 'liveBroadcastContent': 'none', 'publishTime': '2025-03-08T13:00:32Z'}}, {'kind': 'youtube#searchResult', 'etag': 'uKgW9LRXmc7sClTYUg2mugpfry0', 'id': {'kind': 'youtube#video', 'videoId': 'obf0Fc2h4xk'}, 'snippet': {'publishedAt': '2024-10-16T12:32:00Z', 'channelId': 'UCAzgSzH5ggTr4AC9SYVbYdw', 'title': '귀티나는 투명메이크업', 'description': 'thickuongkombucha.', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/obf0Fc2h4xk/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/obf0Fc2h4xk/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/obf0Fc2h4xk/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '앗이슈', 'liveBroadcastContent': 'none', 'publishTime': '2024-10-16T12:32:00Z'}}, {'kind': 'youtube#searchResult', 'etag': 'AyahhT0iicNS_pcAPkHIIbEiKi0', 'id': {'kind': 'youtube#video', 'videoId': 'HmcZhETZTZw'}, 'snippet': {'publishedAt': '2025-03-07T09:51:33Z', 'channelId': 'UCn_fZLXut_Tj9-QihG_9l0g', 'title': '아이폰16pro로 찍은 따뜻한 포근 핑크메이크업🩰\U0001fa76 | 요즘 최애 블러셔&amp;립 조합✨ +콘텐츠 고민 살짝💭', 'description': '이 영상은 유료 광고가 포함되어 있지 않습니다. 이 영상은 노출 의무가 없는 무상제공제품이 포함되어 있습니다. ✱ Contact ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/HmcZhETZTZw/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/HmcZhETZTZw/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/HmcZhETZTZw/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '안다 ANDA', 'liveBroadcastContent': 'none', 'publishTime': '2025-03-07T09:51:33Z'}}, {'kind': 'youtube#searchResult', 'etag': '_zsW8KzUu-YcKNhfP3XCftOYPb8', 'id': {'kind': 'youtube#video', 'videoId': 'Wh92JSWEy64'}, 'snippet': {'publishedAt': '2025-03-07T11:05:28Z', 'channelId': 'UCcNYkzLMSkSiYaiAYjUNzRg', 'title': '˚₊‧꒰ა갈웜 신 청하 구운 로즈 메이크업 ໒꒱ ‧₊˚ | 눈 가로 길이 확장법과 땅콩형 커버 ・ 존예 가을 웜톤 립조합', 'description': '가을웜톤 #청하 #청하메이크업 #갈웜메이크업 #모카무스 #청하스트레스 #웜톤메이크업 #쿨톤모카무스 #땅콩형커버 #트임메이크업 ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/Wh92JSWEy64/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/Wh92JSWEy64/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/Wh92JSWEy64/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '김크리스탈 KimCrystal', 'liveBroadcastContent': 'none', 'publishTime': '2025-03-07T11:05:28Z'}}, {'kind': 'youtube#searchResult', 'etag': 'cLOv73-RFXh2fRLIZxud7VbwoIU', 'id': {'kind': 'youtube#video', 'videoId': 'YJK3MNlMZSE'}, 'snippet': {'publishedAt': '2024-09-20T10:02:44Z', 'channelId': 'UCW67yGQxNNMnLqRHyaTjygA', 'title': '‼️탁한피부 교정‼️내추럴버전🌿#makeuptutorial #kbeauty #홍이모', 'description': '영상속 립& 치크제품 https://youtu.be/oodPVkEFnTA?si=BqYAsIHo_kumsGii.', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/YJK3MNlMZSE/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/YJK3MNlMZSE/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/YJK3MNlMZSE/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': "Hong's MakeuPlay 홍이모", 'liveBroadcastContent': 'none', 'publishTime': '2024-09-20T10:02:44Z'}}, {'kind': 'youtube#searchResult', 'etag': 'CDI9lNjyrD-xWX6HtphQi-EVxcU', 'id': {'kind': 'youtube#video', 'videoId': 'sbGyexhXG9k'}, 'snippet': {'publishedAt': '2024-06-23T13:20:02Z', 'channelId': 'UCURnLWTrLZVv_KiVaeZakog', 'title': '그냥 다 큰 메이크업 (feat.시네)', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/sbGyexhXG9k/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/sbGyexhXG9k/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/sbGyexhXG9k/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'Jiwon 지원', 'liveBroadcastContent': 'none', 'publishTime': '2024-06-23T13:20:02Z'}}, {'kind': 'youtube#searchResult', 'etag': 'o-d7bXmmTPiAjVr01EjwKWP-d7Q', 'id': {'kind': 'youtube#video', 'videoId': 'SrN8ySFRqsE'}, 'snippet': {'publishedAt': '2024-12-06T08:50:30Z', 'channelId': 'UC7R377JtSnWUAH3bIDX3mZw', 'title': '메이크업 하나로 눈 크기 사기치는 법', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/SrN8ySFRqsE/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/SrN8ySFRqsE/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/SrN8ySFRqsE/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '프랑수아 FRANSUA', 'liveBroadcastContent': 'none', 'publishTime': '2024-12-06T08:50:30Z'}}, {'kind': 'youtube#searchResult', 'etag': 'f4OW_jWzGNNDJ4bo2GF72m6Cxq4', 'id': {'kind': 'youtube#video', 'videoId': 'g_M3DdZpvjc'}, 'snippet': {'publishedAt': '2025-01-07T09:00:46Z', 'channelId': 'UCggh84Wxw6yTuCu9Yl8BQGw', 'title': '모공 하나 없는, 아이돌 피부 비결?? #뷰티 #메이크업 #makeup #꿀팁 #beauty #kbeauty', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/g_M3DdZpvjc/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/g_M3DdZpvjc/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/g_M3DdZpvjc/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '뭐해윤지', 'liveBroadcastContent': 'none', 'publishTime': '2025-01-07T09:00:46Z'}}, {'kind': 'youtube#searchResult', 'etag': 'LnkN-mWMeqJq_zpiYI_0zPr-aYE', 'id': {'kind': 'youtube#video', 'videoId': 'LijNldo4nLs'}, 'snippet': {'publishedAt': '2025-01-19T10:00:17Z', 'channelId': 'UCW67yGQxNNMnLqRHyaTjygA', 'title': '‼️요즘 송혜교 미모 장난아님 송혜교 메이크업 따라잡기 #makeuptutorial #kbeuty #홍이모 #송혜교', 'description': '영상 속 제품   MAKE UP FOR EVER HD SKIN 컨실러 1.1(N) 45000 KRW ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/LijNldo4nLs/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/LijNldo4nLs/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/LijNldo4nLs/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': "Hong's MakeuPlay 홍이모", 'liveBroadcastContent': 'none', 'publishTime': '2025-01-19T10:00:17Z'}}, {'kind': 'youtube#searchResult', 'etag': '_iMVq9yvaBc2FhEWJ64eB2XdWZQ', 'id': {'kind': 'youtube#video', 'videoId': 'isxvXAdEKJg'}, 'snippet': {'publishedAt': '2024-01-15T09:01:02Z', 'channelId': 'UCQG5MOnlAl5nUDR_JFOrrxA', 'title': '의외로 잘 모르는 화장 절대 안무너지는 방법 30초면 끝!', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/isxvXAdEKJg/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/isxvXAdEKJg/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/isxvXAdEKJg/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '림온 RIMON', 'liveBroadcastContent': 'none', 'publishTime': '2024-01-15T09:01:02Z'}}, {'kind': 'youtube#searchResult', 'etag': 'Gj-fIP7nEuL4CxIihdR5Xxcq3eM', 'id': {'kind': 'youtube#video', 'videoId': 'PGR_Q_jiiGA'}, 'snippet': {'publishedAt': '2024-09-12T08:00:16Z', 'channelId': 'UC7c3tVADFRIHrl1t3MDTzEQ', 'title': '그럼 자기 페라리는?    #마티 #메이크업 #커플', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/PGR_Q_jiiGA/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/PGR_Q_jiiGA/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/PGR_Q_jiiGA/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'MATI LAND 마티랜드', 'liveBroadcastContent': 'none', 'publishTime': '2024-09-12T08:00:16Z'}}, {'kind': 'youtube#searchResult', 'etag': '-C14ksxJmAwHwH4CODG-j0F33hM', 'id': {'kind': 'youtube#video', 'videoId': 'iDOoA6t2th8'}, 'snippet': {'publishedAt': '2023-10-11T06:07:22Z', 'channelId': 'UCGB2bzMjIZhnaSDUDy2LEZA', 'title': '🇺🇸vs🇰🇷 student makeup comparison 🤓 미국 vs 한국 학생 메이크업 비교!', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/iDOoA6t2th8/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/iDOoA6t2th8/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/iDOoA6t2th8/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'Jooshica', 'liveBroadcastContent': 'none', 'publishTime': '2023-10-11T06:07:22Z'}}, {'kind': 'youtube#searchResult', 'etag': 'f1C0T1aGE6YwTPiPd4fveLZ2uw8', 'id': {'kind': 'youtube#video', 'videoId': '8cLSXqlwt_s'}, 'snippet': {'publishedAt': '2024-12-05T23:39:58Z', 'channelId': 'UCwyR-5gp7NCd-2DwLtdCtcw', 'title': '무쌍 눈이 2배 커지는 눈화장 방법', 'description': '무쌍이라서 속쌍하다면?! 쌍테를 붙이는것도 힘든 똥손이라면?! 그려주자! 라인 안쪽을 좀더 어둡게! 자연스럽게 스머징해주는게 젤 ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/8cLSXqlwt_s/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/8cLSXqlwt_s/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/8cLSXqlwt_s/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '뷰티바이쥬씨 BEAUTY by JUICY', 'liveBroadcastContent': 'none', 'publishTime': '2024-12-05T23:39:58Z'}}, {'kind': 'youtube#searchResult', 'etag': '0qQPm_QqllvRrCE-OHW4N6xaaFM', 'id': {'kind': 'youtube#video', 'videoId': 'RoZItHGElvM'}, 'snippet': {'publishedAt': '2024-11-22T11:27:51Z', 'channelId': 'UCUKmLlnlIuyci4bPVLvZXjw', 'title': '수능 끝난 고등학생 자습시간 20초 퀵메이크업 #shorts#makeup', 'description': '제품정보 매드피치 글레이즈드 글로우 쿠션 21호 토니모리 립앤치크 01호 프라다 모노크롬 립스틱 B101티에폴로 네이밍 루트핏 ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/RoZItHGElvM/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/RoZItHGElvM/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/RoZItHGElvM/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '고우리 Go uri', 'liveBroadcastContent': 'none', 'publishTime': '2024-11-22T11:27:51Z'}}, {'kind': 'youtube#searchResult', 'etag': 'vl5UOKB6f6L9Tujb2HB5AI9DRDU', 'id': {'kind': 'youtube#video', 'videoId': '4ijlP53G3ak'}, 'snippet': {'publishedAt': '2024-09-20T11:49:15Z', 'channelId': 'UCGbRYhxhgxau3h92-SiEuxA', 'title': '얼굴 싹 다 갈아엎는 무쌍메이크업', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/4ijlP53G3ak/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/4ijlP53G3ak/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/4ijlP53G3ak/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '이노마 nomma', 'liveBroadcastContent': 'none', 'publishTime': '2024-09-20T11:49:15Z'}}, {'kind': 'youtube#searchResult', 'etag': '1IIEaKOfXHXyuei04nLrvQil8LQ', 'id': {'kind': 'youtube#video', 'videoId': 'nhAGjJwylaY'}, 'snippet': {'publishedAt': '2025-03-07T11:01:09Z', 'channelId': 'UCvpD0KP2b7nVLbEAydjjNaQ', 'title': '핑크의 악마👿\U0001fa77 지젤 메이크업 해보았습니다🌙', 'description': "ENG/JPN SUB ON ✦ 이 영상은 '스킨1004'의 유료광고를 포함하고 있습니다. ✦ 애플 모바일 기기에서의 색감이 가장 정확합니다.", 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/nhAGjJwylaY/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/nhAGjJwylaY/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/nhAGjJwylaY/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '코코초 COCOCHO', 'liveBroadcastContent': 'none', 'publishTime': '2025-03-07T11:01:09Z'}}, {'kind': 'youtube#searchResult', 'etag': 'KPKBPhZ_DPHRgofuae_pSfnxQU0', 'id': {'kind': 'youtube#video', 'videoId': 'QMLZ_xIvoJA'}, 'snippet': {'publishedAt': '2024-03-26T10:00:17Z', 'channelId': 'UCQG5MOnlAl5nUDR_JFOrrxA', 'title': '요즘 속광 메이크업이 유행이야?! 귀티나는광메이크업 꿀팁 방출! 잘못하면 빈티나요.. #베이스메이크업', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/QMLZ_xIvoJA/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/QMLZ_xIvoJA/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/QMLZ_xIvoJA/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': '림온 RIMON', 'liveBroadcastContent': 'none', 'publishTime': '2024-03-26T10:00:17Z'}}, {'kind': 'youtube#searchResult', 'etag': 'PL9dKleVgRv2P8XK6f2nqhm5EBI', 'id': {'kind': 'youtube#video', 'videoId': '9TKXnODJJd4'}, 'snippet': {'publishedAt': '2025-01-12T11:03:17Z', 'channelId': 'UCa5K5UpYN-JnHSgOe_tHrEw', 'title': '나는 또 어김없이 도쿄에서 메이크업 해 #광고', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/9TKXnODJJd4/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i

[]

In [ ]:
type_df_frame = pd.DataFrame(type_youtubers, columns=['title', 'channel_id', 'country', 'subs'])
print(type_df_frame.head())
print(type_df_frame.info())

Empty DataFrame
Columns: [title, channel_id, country, subs]
Index: []
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       0 non-null      object
 1   channel_id  0 non-null      object
 2   country     0 non-null      object
 3   subs        0 non-null      object
dtypes: object(4)
memory usage: 132.0+ bytes
None

In [ ]:
video_df_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       37 non-null     object
 1   channel_id  37 non-null     object
 2   country     37 non-null     object
 3   subs        37 non-null     int64
dtypes: int64(1), object(3)
memory usage: 1.3+ KB

In [ ]:
video_df_korea = df_frame.loc[df_frame['country']=='KR']
video_df_korea

                        title                channel_id country   subs
32                  1분뷰티 셀프피부  UCVuxljGhpSkXztzk8X6vlMQ      KR  63100
33         신지훈의 뷰티비 - make up  UC8ztEunx83lflUWENoMdAuA      KR  35800
34            리아뷰티 Lia Beauty  UCAXVvaPOmb19eThQR-fLpKg      KR  10500
35                       찌니뷰티  UCwXb4wWwhFNYHedz_g9Q8qw      KR  12500
36            후메이크업whozmakeup  UCw30nojSCDiqv1JO0Tu1Mrw      KR  50000
37                    엘리 메이크업  UCT2aO5ha79Yu-HN6U_PNlCg      KR  59700
38                   최민낯_민낯뷰티  UCjye-yA-LIb7WXKRnGR-fzA      KR  15300
39  화장의 신프로 Makeup Shin Prof.  UCyAmQPPLTsy-B2NhQKo3KMg      KR  16200
40                       뷰티랩스  UC9BEygCDE2B7vB5tIgpsIDg      KR  44300
41          고수뷰티 GOSOO BEAUTY  UC53ZbBCHU_N49ykaxeCcAGg      KR  52400
42                     디오드 뷰티  UCJf_CZp5YjzW4GM6G2uZC6w      KR  48300

### 이사배 채널 재생목록 가져오기

In [ ]:
# YouTube API 키
API_KEY = "AIzaSyAXcyW687GW8DvGks2T2OjKitE-6mHB7vs"
BASE_URL = "https://www.googleapis.com/youtube/v3"

search_url = f"{BASE_URL}/search"
params = {
    "part": "snippet",
    "q": "RISABAE",  # 한국어 키워드 검색  # 한국 유튜버 검색
    "maxResults": 50,
    "order": "relevance",
    "type": "channel",
    "key": API_KEY
}

search_response = requests.get(search_url, params=params).json()

search_response

{'kind': 'youtube#searchListResponse',
 'etag': 'ac3PYbNoVA9BU7_2p7ptFJZwoLQ',
 'nextPageToken': 'CDIQAA',
 'regionCode': 'US',
 'pageInfo': {'totalResults': 154, 'resultsPerPage': 50},
 'items': [{'kind': 'youtube#searchResult',
   'etag': 'huPIKVCQe7XEkVGxL98xpnlSrXU',
   'id': {'kind': 'youtube#channel', 'channelId': 'UC9kmlDcqksaOnCkC_qzGacA'},
   'snippet': {'publishedAt': '2015-07-14T02:12:09Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': 'RISABAE',
    'description': 'risabaeofficial@gmail.com https://instagram.com/risabae_art.',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lB8AyOqh_MxT6LcGodOH8flrInTGkPO8KWwrVM5dl7Jhw=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lB8AyOqh_MxT6LcGodOH8flrInTGkPO8KWwrVM5dl7Jhw=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lB8AyOqh_MxT6LcGodOH8flrInTGkPO8KWwrVM5dl7Jhw=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'RISABAE',
    'liveBroadcastContent': 'none',
    'publishTime': '2015-07-14T02:12:09Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'jDqY4NhKDTodd_qAOI0k38DPI7U',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCmtJ_YLCIf0oNWig8zP7Uow'},
   'snippet': {'publishedAt': '2018-06-08T11:42:41Z',
    'channelId': 'UCmtJ_YLCIf0oNWig8zP7Uow',
    'title': 'RISABAE - Topic',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/qkaUVZeL3OY5YT82dtK6q5uAhufyencAF4COQDHpmcW0A1phFBWTC7QN0gsagqC4IFDu2_Jo=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/qkaUVZeL3OY5YT82dtK6q5uAhufyencAF4COQDHpmcW0A1phFBWTC7QN0gsagqC4IFDu2_Jo=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/qkaUVZeL3OY5YT82dtK6q5uAhufyencAF4COQDHpmcW0A1phFBWTC7QN0gsagqC4IFDu2_Jo=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'RISABAE - Topic',
    'liveBroadcastContent': 'none',
    'publishTime': '2018-06-08T11:42:41Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'V5322CqMGRQ-r883TAjCEGThdH4',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCWzchUeR9Yd-tJIVmyhZnrA'},
   'snippet': {'publishedAt': '2018-06-02T13:23:31Z',
    'channelId': 'UCWzchUeR9Yd-tJIVmyhZnrA',
    'title': 'RealRISABAE 리얼리사배',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_m1As1KLRMRUeSaGoYgC2yEiyDTtBMmh9iWDAPylBLmlQ=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_m1As1KLRMRUeSaGoYgC2yEiyDTtBMmh9iWDAPylBLmlQ=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_m1As1KLRMRUeSaGoYgC2yEiyDTtBMmh9iWDAPylBLmlQ=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'RealRISABAE 리얼리사배',
    'liveBroadcastContent': 'none',
    'publishTime': '2018-06-02T13:23:31Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'D4bqNDwEDWax6xlpplRr9mbOyOQ',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCJrrrARGYJTzmaCkT-PKRmw'},
   'snippet': {'publishedAt': '2012-09-27T08:16:16Z',
    'channelId': 'UCJrrrARGYJTzmaCkT-PKRmw',
    'title': '사배#둠칫둠칫',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_n3MXYKb2s0cRDEoclvStpI0jDlXtco1aEWe8AAcPU5c2U=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_n3MXYKb2s0cRDEoclvStpI0jDlXtco1aEWe8AAcPU5c2U=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_n3MXYKb2s0cRDEoclvStpI0jDlXtco1aEWe8AAcPU5c2U=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': '사배#둠칫둠칫',
    'liveBroadcastContent': 'none',
    'publishTime': '2012-09-27T08:16:16Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '1ht0JH9M0KTw8oGs9Znp40tnJLo',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCpRnDugdyX_4iy_RKcmrbsw'},
   'snippet': {'publishedAt': '2023-06-18T14:22:50Z',
    'channelId': 'UCpRnDugdyX_4iy_RKcmrbsw',
    'title': 'Risa bae🎀',
    'description': 'متنسوش تعملو الايك والاشتراك في القناه وتفعيل الجرس عشان يوصلوكو كل جديد وبيكم انشاء الله نوصل المليون.',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/4m0HQla8ZiEIj-QiGAJEl0eYMiYFZpvR7py0B9xLNQSQEk5Rzgg4SZlsPWMzmoTDYLGG3kV7yg=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/4m0HQla8ZiEIj-QiGAJEl0eYMiYFZpvR7py0B9xLNQSQEk5Rzgg4SZlsPWMzmoTDYLGG3kV7yg=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/4m0HQla8ZiEIj-QiGAJEl0eYMiYFZpvR7py0B9xLNQSQEk5Rzgg4SZlsPWMzmoTDYLGG3kV7yg=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Risa bae🎀',
    'liveBroadcastContent': 'none',
    'publishTime': '2023-06-18T14:22:50Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'eGGEfNUMqCoyXjqCBq_oYF2yjVw',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCtjqB-DNXr3FfaDqnERkX1A'},
   'snippet': {'publishedAt': '2022-08-10T09:55:35Z',
    'channelId': 'UCtjqB-DNXr3FfaDqnERkX1A',
    'title': 'Risa Bae',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lkvZL6_kz1dOZZNlAfaTAAvzD815r_d0GFkV8C9bR31YRZeGPylgyyE4sM5v8Yxu6Veg=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lkvZL6_kz1dOZZNlAfaTAAvzD815r_d0GFkV8C9bR31YRZeGPylgyyE4sM5v8Yxu6Veg=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lkvZL6_kz1dOZZNlAfaTAAvzD815r_d0GFkV8C9bR31YRZeGPylgyyE4sM5v8Yxu6Veg=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Risa Bae',
    'liveBroadcastContent': 'none',
    'publishTime': '2022-08-10T09:55:35Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '-CtaNh3X9OkBDhaSg4RsXz4qjsE',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCvykDFVBSDMLhcD6ElNGljw'},
   'snippet': {'publishedAt': '2024-01-29T03:47:14Z',
    'channelId': 'UCvykDFVBSDMLhcD6ElNGljw',
    'title': 'Risa Bae',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lawf9yWTQpDKE0MLo3587nhlwH_ppxDQse0Bw_-WWV25kHUsQnoRSTBnBBFdxj69wZBg=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lawf9yWTQpDKE0MLo3587nhlwH_ppxDQse0Bw_-WWV25kHUsQnoRSTBnBBFdxj69wZBg=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lawf9yWTQpDKE0MLo3587nhlwH_ppxDQse0Bw_-WWV25kHUsQnoRSTBnBBFdxj69wZBg=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Risa Bae',
    'liveBroadcastContent': 'none',
    'publishTime': '2024-01-29T03:47:14Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'L1B7HwR_T-kCKEJ0dgRHS4LXvMQ',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCMQZ83kUheJoJbCPmMWDstw'},
   'snippet': {'publishedAt': '2021-08-27T02:55:09Z',
    'channelId': 'UCMQZ83kUheJoJbCPmMWDstw',
    'title': 'Risa Bae',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lawf9yWTQpDKE0MLo3587nhlwH_ppxDQse0Bw_-WWV25kHUsQnoRSTBnBBFdxj69wZBg=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lawf9yWTQpDKE0MLo3587nhlwH_ppxDQse0Bw_-WWV25kHUsQnoRSTBnBBFdxj69wZBg=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lawf9yWTQpDKE0MLo3587nhlwH_ppxDQse0Bw_-WWV25kHUsQnoRSTBnBBFdxj69wZBg=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Risa Bae',
    'liveBroadcastContent': 'none',
    'publishTime': '2021-08-27T02:55:09Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'x3YLovWvLcp_nsRAuulmpDIcMIU',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCSqkdH28Dzt6Ae-OHPtJO-A'},
   'snippet': {'publishedAt': '2021-11-07T13:32:45Z',
    'channelId': 'UCSqkdH28Dzt6Ae-OHPtJO-A',
    'title': 'Risa bae',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lkvZL6_kz1dOZZNlAfaTAAvzD815r_d0GFkV8C9bR31YRZeGPylgyyE4sM5v8Yxu6Veg=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lkvZL6_kz1dOZZNlAfaTAAvzD815r_d0GFkV8C9bR31YRZeGPylgyyE4sM5v8Yxu6Veg=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lkvZL6_kz1dOZZNlAfaTAAvzD815r_d0GFkV8C9bR31YRZeGPylgyyE4sM5v8Yxu6Veg=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Risa bae',
    'liveBroadcastContent': 'none',
    'publishTime': '2021-11-07T13:32:45Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'YcmVCLGHO-ekvO94wvB0faK1TBs',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCh9thaQzLEh84NawNZoY9nQ'},
   'snippet': {'publishedAt': '2023-06-05T05:05:57Z',
    'channelId': 'UCh9thaQzLEh84NawNZoY9nQ',
    'title': 'RISA BAE',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/8m8qrCcDMl9sTsUKdo8lJlPMK3xL4CAeXCXuKLhlBxEIgbop1QGvkmUr9u-V6peq_n5ZWR1b=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/8m8qrCcDMl9sTsUKdo8lJlPMK3xL4CAeXCXuKLhlBxEIgbop1QGvkmUr9u-V6peq_n5ZWR1b=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/8m8qrCcDMl9sTsUKdo8lJlPMK3xL4CAeXCXuKLhlBxEIgbop1QGvkmUr9u-V6peq_n5ZWR1b=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'RISA BAE',
    'liveBroadcastContent': 'none',
    'publishTime': '2023-06-05T05:05:57Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'laOTQ0rTHT9gKlFvUmLTk2eGDyY',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCVafDoCDgHW_9TErR3huTeQ'},
   'snippet': {'publishedAt': '2020-07-04T09:15:12Z',
    'channelId': 'UCVafDoCDgHW_9TErR3huTeQ',
    'title': 'Risa Bae',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_mKiYnAsTug1mrVw8cSVTgmCQUYkMQAtCYsLeZ2kA4=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_mKiYnAsTug1mrVw8cSVTgmCQUYkMQAtCYsLeZ2kA4=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_mKiYnAsTug1mrVw8cSVTgmCQUYkMQAtCYsLeZ2kA4=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Risa Bae',
    'liveBroadcastContent': 'none',
    'publishTime': '2020-07-04T09:15:12Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'aA5t4C7tAh66sn1TEr00hd3Sjpw',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCs7Ey95VOkqoZzUIRtaiKdQ'},
   'snippet': {'publishedAt': '2018-10-14T06:09:54Z',
    'channelId': 'UCs7Ey95VOkqoZzUIRtaiKdQ',
    'title': 'Risa Bae',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_m-myceu33GaWJ-EQsdQCnGFg_TdYEsp0S0ul9tZvg=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_m-myceu33GaWJ-EQsdQCnGFg_TdYEsp0S0ul9tZvg=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_m-myceu33GaWJ-EQsdQCnGFg_TdYEsp0S0ul9tZvg=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Risa Bae',
    'liveBroadcastContent': 'none',
    'publishTime': '2018-10-14T06:09:54Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '0BbegHjEP4HYiri_7qgC1_f3-_M',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCLRiDKEZAxHVIeOTQWBX7IQ'},
   'snippet': {'publishedAt': '2021-09-08T04:41:04Z',
    'channelId': 'UCLRiDKEZAxHVIeOTQWBX7IQ',
    'title': 'Risa BAE',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lawf9yWTQpDKE0MLo3587nhlwH_ppxDQse0Bw_-WWV25kHUsQnoRSTBnBBFdxj69wZBg=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lawf9yWTQpDKE0MLo3587nhlwH_ppxDQse0Bw_-WWV25kHUsQnoRSTBnBBFdxj69wZBg=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lawf9yWTQpDKE0MLo3587nhlwH_ppxDQse0Bw_-WWV25kHUsQnoRSTBnBBFdxj69wZBg=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Risa BAE',
    'liveBroadcastContent': 'none',
    'publishTime': '2021-09-08T04:41:04Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'qjvN5_qx8l3kiNdzujNwu0GCg20',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCUcpAMSKqh8S9S1nnxuaQBg'},
   'snippet': {'publishedAt': '2021-02-20T21:20:26Z',
    'channelId': 'UCUcpAMSKqh8S9S1nnxuaQBg',
    'title': 'MY TREASURE',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/CpvC33nJAkXqXlpUjTsCLJWe5WdteRwLzPK2U9sJOg4iU25baGj2OpGrGPRsX9zhUXAqgDOmzA=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/CpvC33nJAkXqXlpUjTsCLJWe5WdteRwLzPK2U9sJOg4iU25baGj2OpGrGPRsX9zhUXAqgDOmzA=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/CpvC33nJAkXqXlpUjTsCLJWe5WdteRwLzPK2U9sJOg4iU25baGj2OpGrGPRsX9zhUXAqgDOmzA=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'MY TREASURE',
    'liveBroadcastContent': 'none',
    'publishTime': '2021-02-20T21:20:26Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'GOIiTTBgsx5nPhKKa2QrUkV2i3Q',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCXjxON1nNxBYsoee11BpZww'},
   'snippet': {'publishedAt': '2022-05-02T17:39:17Z',
    'channelId': 'UCXjxON1nNxBYsoee11BpZww',
    'title': 'ʏᴏᴜɪʟ',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/Nuw1WPZD_B9CUJ2LwrhrnpxYWvSuSiOitL52xPiqWU7jPlktbD_xMq5Cn_DAvdVe8m_LuD2e4w=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/Nuw1WPZD_B9CUJ2LwrhrnpxYWvSuSiOitL52xPiqWU7jPlktbD_xMq5Cn_DAvdVe8m_LuD2e4w=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/Nuw1WPZD_B9CUJ2LwrhrnpxYWvSuSiOitL52xPiqWU7jPlktbD_xMq5Cn_DAvdVe8m_LuD2e4w=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'ʏᴏᴜɪʟ',
    'liveBroadcastContent': 'none',
    'publishTime': '2022-05-02T17:39:17Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'ZvkvyIe_Va21grHmJfhM6hZdZQg',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCOC2NT3ApbQTSuKsdJF9pEg'},
   'snippet': {'publishedAt': '2024-08-01T16:21:03Z',
    'channelId': 'UCOC2NT3ApbQTSuKsdJF9pEg',
    'title': 'Isabella ',
    'description': '',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/voXksmjWH2_ylWDOTyVLI3mX6kNf-rpazD588FAfekWgiEoFyIjI0Mb_NHtOZupAlGetGb40sJM=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/voXksmjWH2_ylWDOTyVLI3mX6kNf-rpazD588FAfekWgiEoFyIjI0Mb_NHtOZupAlGetGb40sJM=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/voXksmjWH2_ylWDOTyVLI3mX6kNf-rpazD588FAfekWgiEoFyIjI0Mb_NHtOZupAlGetGb40sJM=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Isabella ',
    'liveBroadcastContent': 'none',
    'publishTime': '2024-08-01T16:21:03Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'krsYMjYzNzM4LcKPKJs8hGSo1pA',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCy9sBWBeDSBiohmBgH_1JnQ'},
   'snippet': {'publishedAt': '2025-02-26T15:19:39Z',
    'channelId': 'UCy9sBWBeDSBiohmBgH_1JnQ',
    'title': 'Imlinos',
    'description': 'Felix bias/lee know from @2sillystays Stay, blink, villain, engene, atiny, moa, midzy, monstiez Goofy ahh Sub to @2sillystays.',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/4wMl1XNs5pS80NwmMEA_0vpgNdk0UHAMzpxsoG0vkp3wke58ROZwllI0QQsKwvYEdylHj_krcJ8=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/4wMl1XNs5pS80NwmMEA_0vpgNdk0UHAMzpxsoG0vkp3wke58ROZwllI0QQsKwvYEdylHj_krcJ8=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/4wMl1XNs5pS80NwmMEA_0vpgNdk0UHAMzpxsoG0vkp3wke58ROZwllI0QQsKwvYEdylHj_krcJ8=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Imlinos',
    'liveBroadcastContent': 'none',
    'publishTime': '2025-02-26T15:19:39Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'tLbfNHDdn44JXVKVasxWmJrVDAE',
   'id': {'kind': 'youtube#channel', 'channelId': 'UC2hAzc-OArU-hGmX6DlxEDA'},
   'snippet': {'publishedAt': '2025-02-01T10:02:22Z',
    'channelId': 'UC2hAzc-OArU-hGmX6DlxEDA',
    'title': 'Lilithlovesmintchoco',
    'description': 'Hey there! I react to K-pop, J-pop, P-pop, and beyond—breaking down music videos, live performances, interviews, and ...',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ULBzPoymPYP2ViL6Zj_r0ymXGZMRAQKlgZfbVWx3A9cszyzVQCvcITsnPSH2Kyt_QYtNiiIgZQ=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/ULBzPoymPYP2ViL6Zj_r0ymXGZMRAQKlgZfbVWx3A9cszyzVQCvcITsnPSH2Kyt_QYtNiiIgZQ=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/ULBzPoymPYP2ViL6Zj_r0ymXGZMRAQKlgZfbVWx3A9cszyzVQCvcITsnPSH2Kyt_QYtNiiIgZQ=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'Lilithlovesmintchoco',
    'liveBroadcastContent': 'none',
    'publishTime': '2025-02-01T10:02:22Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'pElQdu17pjSs7TihNuJzVXDNJ0M',
   'id': {'kind': 'youtube#channel', 'channelId': 'UC1e4lLd9BlqumF-vl08dCXg'},
   'snippet': {'publishedAt': '2020-11-24T11:41:26Z',
    'channelId': 'UC1e4lLd9BlqumF-vl08dCXg',
    'title': '카지노대장16',
    'description': '미션 & 아바타 & 여행문의 / 카카오톡 DJ8999 24시간 언제든지 편하실때 연락주세요 ! 환영합니다 ! 캄보디아 시아누크빌 현지 호텔 ...',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/K1367pCnyu5X2Ye-tbsrRtt6c5xSptbLK345NKX2Zu8WsO4_XO19ae-GnbILyLf2NlHB9cPc=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/K1367pCnyu5X2Ye-tbsrRtt6c5xSptbLK345NKX2Zu8WsO4_XO19ae-GnbILyLf2NlHB9cPc=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/K1367pCnyu5X2Ye-tbsrRtt6c5xSptbLK345NKX2Zu8WsO4_XO19ae-GnbILyLf2NlHB9cPc=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': '카지노대장16',
    'liveBroadcastContent': 'none',
    'publishTime': '2020-11-24T11:41:26Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'lpNlXpD7LTubQwyXkFiGkpiHXdw',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCTzQJnCH5eJIq_ux7Jos5iA'},
   'snippet': {'publishedAt': '2016-07-27T18:42:10Z',
    'channelId': 'UCTzQJnCH5eJIq_ux7Jos5iA',
    'title': 'lililiks',
    'description': 'Переводчик всего и всех Любимое место, посвященное любимому котику https://t.me/bubble_felix Хёнликсер во всех ...',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/zZGgQ7ts5alODH9BRowG4d4UzI_o-hjvniHBEic_2YyTZRGe2HFOu_q-ulkjbGQytehTkMTUKg=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/zZGgQ7ts5alODH9BRowG4d4UzI_o-hjvniHBEic_2YyTZRGe2HFOu_q-ulkjbGQytehTkMTUKg=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/zZGgQ7ts5alODH9BRowG4d4UzI_o-hjvniHBEic_2YyTZRGe2HFOu_q-ulkjbGQytehTkMTUKg=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'lililiks',
    'liveBroadcastContent': 'none',
    'publishTime': '2016-07-27T18:42:10Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'JzLo7NMZGfhHuNRi2xJx3sNnNDc',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCX84o3OTUVgc2cnII3MWkdw'},
   'snippet': {'publishedAt': '2025-02-08T10:13:37Z',
    'channelId': 'UCX84o3OTUVgc2cnII3MWkdw',
    'title': 'ꌗ𝙺Z̶𝑪𝐻oWA̷',
    'description': "ѕтяαу кι∂ѕ вєѕт #ι'м ѕтαу #ӄɨʟʟɛʀ!? #chríshαlfσnєthσusαnd #whyleedoesn'tknow ...",
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/LRJwKfy0dJeyL0vPz2noYxvixp1G4yVYFEeBTC6cx5jGvhkbpnsoAfAZTPnNI152TygyeJXcXA=s88-c-k-c0xffffffff-no-rj-mo'},
     'medium': {'url': 'https://yt3.ggpht.com/LRJwKfy0dJeyL0vPz2noYxvixp1G4yVYFEeBTC6cx5jGvhkbpnsoAfAZTPnNI152TygyeJXcXA=s240-c-k-c0xffffffff-no-rj-mo'},
     'high': {'url': 'https://yt3.ggpht.com/LRJwKfy0dJeyL0vPz2noYxvixp1G4yVYFEeBTC6cx5jGvhkbpnsoAfAZTPnNI152TygyeJXcXA=s800-c-k-c0xffffffff-no-rj-mo'}},
    'channelTitle': 'ꌗ𝙺Z̶𝑪𝐻oWA̷',
    'liveBroadcastContent': 'none',
    'publishTime': '2025-02-08T10:13:37Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'kBioJMetqoECe3sSCEwIz90ppKM',
   'id': {'kind': 'youtube#channel', 'channelId': 'UCwiv6RyIIZn7JCOEKTpiffQ'},
   'snippet': {'publishedAt': '2022-08-31T00:29:02Z',
    'channelId': 'UCwiv6RyIIZn7JCOEKTpiffQ',
    'title': 'MoonStaa⁸',
    'description': 'Hii Staa       Please support these 8 talented singers, dancers, rappers, composers, psychologists, comedians, motivators, ...',
    'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/qo6VIrZcTfpqaciXWgB4iiKF0_wnu1z4vbCR2KzPy2v-UL0yPhNq7epFFrxhw1wmuHygOagoeg=s88-c-k-c0xffffffff-no-rj-mo'},

In [ ]:
search_response['items'][0]

{'kind': 'youtube#searchResult',
 'etag': 'huPIKVCQe7XEkVGxL98xpnlSrXU',
 'id': {'kind': 'youtube#channel', 'channelId': 'UC9kmlDcqksaOnCkC_qzGacA'},
 'snippet': {'publishedAt': '2015-07-14T02:12:09Z',
  'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
  'title': 'RISABAE',
  'description': 'risabaeofficial@gmail.com https://instagram.com/risabae_art.',
  'thumbnails': {'default': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lB8AyOqh_MxT6LcGodOH8flrInTGkPO8KWwrVM5dl7Jhw=s88-c-k-c0xffffffff-no-rj-mo'},
   'medium': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lB8AyOqh_MxT6LcGodOH8flrInTGkPO8KWwrVM5dl7Jhw=s240-c-k-c0xffffffff-no-rj-mo'},
   'high': {'url': 'https://yt3.ggpht.com/ytc/AIdro_lB8AyOqh_MxT6LcGodOH8flrInTGkPO8KWwrVM5dl7Jhw=s800-c-k-c0xffffffff-no-rj-mo'}},
  'channelTitle': 'RISABAE',
  'liveBroadcastContent': 'none',
  'publishTime': '2015-07-14T02:12:09Z'}}

In [ ]:
risabae_id = search_response['items'][0]['snippet']['channelId']
risabae_id

'UC9kmlDcqksaOnCkC_qzGacA'

In [ ]:
channel_url = f"{BASE_URL}/channels"
params = {
    "part": "snippet,statistics",
    "id": risabae_id,
    "key": API_KEY
}
channel_response = requests.get(channel_url, params=params).json()

for item in channel_response.get("items", []):
    subs_count = int(item["statistics"].get("subscriberCount", 0))
    country = item.get("snippet", {}).get("country", "Unknown")
    channel_info = (
        item["snippet"]["title"],
        item["id"],
        country,
        subs_count
    )

print(channel_info)

('RISABAE', 'UC9kmlDcqksaOnCkC_qzGacA', 'KR', 2550000)

In [ ]:
playlists_url = f"{BASE_URL}/playlists"
params = {
    "channelId" : 'UC9kmlDcqksaOnCkC_qzGacA',
    "part": "snippet",
    "maxResults" : 20,
    "key" : API_KEY
}

risabae_response = requests.get(playlists_url, params=params).json()

risabae_response

{'kind': 'youtube#playlistListResponse',
 'etag': 'XydLZ6Wl7p3qVHfXJVIk9QKehoA',
 'pageInfo': {'totalResults': 14, 'resultsPerPage': 20},
 'items': [{'kind': 'youtube#playlist',
   'etag': '3zSNlFMzAEC_-UgFmL9SvPno4bU',
   'id': 'PLMQGTAwtel2yCFXqAv_jLpaTpoQ3Uidqu',
   'snippet': {'publishedAt': '2023-06-29T10:26:13.057712Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# 꼼화랑',
    'description': '',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/1R8ZcSW4ASk/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/1R8ZcSW4ASk/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/1R8ZcSW4ASk/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/1R8ZcSW4ASk/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/1R8ZcSW4ASk/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# 꼼화랑', 'description': ''}}},
  {'kind': 'youtube#playlist',
   'etag': 'Lnlk7hOUqCFMbZJq18ZhvqgPYlk',
   'id': 'PLMQGTAwtel2wFEbUB02X_Pch3MxmhEl73',
   'snippet': {'publishedAt': '2022-07-15T02:30:06.965454Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# Shorts',
    'description': '',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/DnvU-yVaYq0/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/DnvU-yVaYq0/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/DnvU-yVaYq0/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/DnvU-yVaYq0/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/DnvU-yVaYq0/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# Shorts', 'description': ''}}},
  {'kind': 'youtube#playlist',
   'etag': 'YlTO-eyDCAtmZPyoUrRWNYHw9Rw',
   'id': 'PLMQGTAwtel2yEjFwBT861tX_NWkoALWxF',
   'snippet': {'publishedAt': '2021-09-08T02:21:33.860809Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# Cover Makeup',
    'description': '',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/UvM-SGVBaJ8/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/UvM-SGVBaJ8/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/UvM-SGVBaJ8/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/UvM-SGVBaJ8/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/UvM-SGVBaJ8/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# Cover Makeup', 'description': ''}}},
  {'kind': 'youtube#playlist',
   'etag': 'LN-dwNoSVcOBKWkQhQ2TNgiTyiY',
   'id': 'PLMQGTAwtel2y14sSeDqhe9PkRgg2Ow1tn',
   'snippet': {'publishedAt': '2017-10-25T18:47:40.34035Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# Back To Basic',
    'description': '',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/RfA4NGT0Z44/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/RfA4NGT0Z44/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/RfA4NGT0Z44/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/RfA4NGT0Z44/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/RfA4NGT0Z44/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# Back To Basic', 'description': ''}}},
  {'kind': 'youtube#playlist',
   'etag': '5MkwBRBphDqnykIBUoyTGaFY9-g',
   'id': 'PLMQGTAwtel2zjGMoHQMpUt9GKnjA7HB8-',
   'snippet': {'publishedAt': '2016-12-19T08:23:32.651433Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# 깡으로 버텨라',
    'description': '메이크업 챌린지 깡으로버텨라!!!',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/6dkN9m-0lWs/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/6dkN9m-0lWs/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/6dkN9m-0lWs/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/6dkN9m-0lWs/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/6dkN9m-0lWs/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# 깡으로 버텨라', 'description': '메이크업 챌린지 깡으로버텨라!!!'}}},
  {'kind': 'youtube#playlist',
   'etag': 'jEQkZJbJFsAZJfbsd-joV7oPnkI',
   'id': 'PLMQGTAwtel2xf6BGEoQb5km4VQj5sv68-',
   'snippet': {'publishedAt': '2016-01-22T01:44:49.872966Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# 무편집 영상',
    'description': '무편집 영상 모음♥',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/zk3dBqFGEWg/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/zk3dBqFGEWg/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/zk3dBqFGEWg/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/zk3dBqFGEWg/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/zk3dBqFGEWg/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# 무편집 영상', 'description': '무편집 영상 모음♥'}}},
  {'kind': 'youtube#playlist',
   'etag': '-I1pLfLqlo8zYAugsZGUmx3FANw',
   'id': 'PLMQGTAwtel2wNUsAfm_ZY597XQHX0VmSB',
   'snippet': {'publishedAt': '2015-11-13T10:50:27.505887Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# Fashion',
    'description': '데일리룩 영상',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/acCK0IEMyzA/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/acCK0IEMyzA/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/acCK0IEMyzA/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/acCK0IEMyzA/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/acCK0IEMyzA/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# Fashion', 'description': '데일리룩 영상'}}},
  {'kind': 'youtube#playlist',
   'etag': 'gsK6AmXm8jB5tzqIL2AHubDZdjo',
   'id': 'PLMQGTAwtel2zKbThprM-NnDBCh5MN6gpm',
   'snippet': {'publishedAt': '2015-09-26T10:30:33.176615Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# Episode',
    'description': '여러 일상 + 방송 뒷이야기!',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/zjRvJvjT5KA/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/zjRvJvjT5KA/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/zjRvJvjT5KA/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/zjRvJvjT5KA/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/zjRvJvjT5KA/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# Episode', 'description': '여러 일상 + 방송 뒷이야기!'}}},
  {'kind': 'youtube#playlist',
   'etag': 'UUtiabiNqn-ahM2BZf3EEw4Ttq4',
   'id': 'PLMQGTAwtel2yJI8giqzufnjqz-f6FTDHl',
   'snippet': {'publishedAt': '2015-09-12T12:21:53.719262Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# 메이크업 진단',
    'description': 'SOS! 메이크업 진단',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/img/no_thumbnail.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/img/no_thumbnail.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/img/no_thumbnail.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# 메이크업 진단', 'description': 'SOS! 메이크업 진단'}}},
  {'kind': 'youtube#playlist',
   'etag': 'AW4Fht6ITuVfinIOSJZyXoEdoqQ',
   'id': 'PLMQGTAwtel2yLnUUWPWEwgK0nMSVb6jRo',
   'snippet': {'publishedAt': '2015-09-11T13:55:03.145802Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# Vlog',
    'description': '',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/u6yGafRu4qA/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/u6yGafRu4qA/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/u6yGafRu4qA/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/u6yGafRu4qA/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/u6yGafRu4qA/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# Vlog', 'description': ''}}},
  {'kind': 'youtube#playlist',
   'etag': 'en6RuTjt_6GbumXPrd0FjxJC3Po',
   'id': 'PLMQGTAwtel2zw4jzgB0lC8QWCnmQ-1c-W',
   'snippet': {'publishedAt': '2015-08-28T07:03:21.670948Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# How to',
    'description': '',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/l0lop8WpXi4/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/l0lop8WpXi4/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/l0lop8WpXi4/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/l0lop8WpXi4/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/l0lop8WpXi4/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# How to', 'description': ''}}},
  {'kind': 'youtube#playlist',
   'etag': 'MgcY6TlaTurBT7rKm_PDOraJpr4',
   'id': 'PLMQGTAwtel2zDF6tpEcL6rOO6l8mXJ-1C',
   'snippet': {'publishedAt': '2015-08-28T06:57:56.02857Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# Collaboration',
    'description': '',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/lvQAbsjnh9c/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/lvQAbsjnh9c/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/lvQAbsjnh9c/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/lvQAbsjnh9c/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/lvQAbsjnh9c/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# Collaboration', 'description': ''}}},
  {'kind': 'youtube#playlist',
   'etag': 'uzPg5KpLUL78BIIZw3VNVZ_VPbQ',
   'id': 'PLMQGTAwtel2zLT3VA4IENL8ic3sSc1FAA',
   'snippet': {'publishedAt': '2015-08-28T06:56:37.353145Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# Concept Makeup Tutorial',
    'description': '컨셉 / 아트 / 커버 메이크업',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/vvfgxV8G1_w/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/vvfgxV8G1_w/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/vvfgxV8G1_w/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/vvfgxV8G1_w/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/vvfgxV8G1_w/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# Concept Makeup Tutorial',
     'description': '컨셉 / 아트 / 커버 메이크업'}}},
  {'kind': 'youtube#playlist',
   'etag': 'ufSxtTk7iREU1S1NmhvPGNAJGt0',
   'id': 'PLMQGTAwtel2z0VcFpBnJI7fHTR8klXMGb',
   'snippet': {'publishedAt': '2015-08-28T06:53:26.235855Z',
    'channelId': 'UC9kmlDcqksaOnCkC_qzGacA',
    'title': '# Makeup Tutorials',
    'description': '다양한 메이크업 튜토리얼!',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/TmFnjy9bEeo/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/TmFnjy9bEeo/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/TmFnjy9bEeo/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/TmFnjy9bEeo/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/TmFnjy9bEeo/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'RISABAE',
    'localized': {'title': '# Makeup Tutorials',
     'description': '다양한 메이크업 튜토리얼!'}}}]}

In [ ]:
len(risabae_response['items'])

14

In [ ]:
risabae_playlists = set()

for i in range(0, len(risabae_response['items'])):
    playlist = risabae_response['items'][i]['snippet']['title']
    risabae_playlists.add(playlist)

print(risabae_playlists)

{'# How to', '# Vlog', '# 깡으로 버텨라', '# Fashion', '# Makeup Tutorials', '# Concept Makeup Tutorial', '# 꼼화랑', '# Shorts', '# Back To Basic', '# Cover Makeup', '# Episode', '# 무편집 영상', '# 메이크업 진단', '# Collaboration'}